# Generated by Django 6.0.4 on 2026-05-22 06:55

import django.db.models.deletion
import tracks.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0002_track_audio_file'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to=tracks.models.upload_media_path, verbose_name='Файл обложки'),
        ),
        migrations.AddField(
            model_name='track',
            name='cover_url',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на обложку'),
        ),
        migrations.AlterField(
            model_name='track',
            name='added_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to=settings.AUTH_USER_MODEL, verbose_name='Добавлено'),
        ),
        migrations.AlterField(
            model_name='track',
            name='artist',
            field=models.CharField(max_length=200, verbose_name='Исполнитель'),
        ),
        migrations.AlterField(
            model_name='track',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='tracks/audio', verbose_name='Файл с аудио'),
        ),
        migrations.AlterField(
            model_name='track',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления'),
        ),
        migrations.AlterField(
            model_name='track',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='track',
            name='video_url',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на видео'),
        ),
    ]
