# Generated by Django 6.0.4 on 2026-05-22 14:36

import tracks.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0003_track_cover_image_track_cover_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to=tracks.models.upload_media_path, verbose_name='Файл с аудио'),
        ),
    ]
